"""add color to label

Revision ID: d00a5662ef4a
Revises: f202dec6bdb9
Create Date: 2026-02-19 21:15:03.246419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00a5662ef4a'
down_revision: Union[str, Sequence[str], None] = 'f202dec6bdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'color')
    # ### end Alembic commands ###
