"""add due date to task

Revision ID: 1fbcbacf5aac
Revises: ed77dd8273a1
Create Date: 2026-01-15 11:57:23.895350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1fbcbacf5aac'
down_revision: Union[str, Sequence[str], None] = 'ed77dd8273a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###
